### ISSUE TITLE
Can't descend down from depth 13

### ISSUE THREAD

**Issue by vi** [Smujb/yet-another-shattered-dungeon#1]
For 2-3 times it just returned back to depth 13 (near the stairs down), then it began crashing (including when attempting to load the save file). Second attempt to load the save file leads to `ERROR: Save file not found...`. After starting a new run that old save is just missing entirely.

```
***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: google
Device: crosshatch
Model: Pixel 3 XL
Manufacturer: Google
Product: crosshatch
SDK: 29
Release: 10

***** APP INFO 
Version: 0.2.6-INDEV
Installed On: 2020-02-18 00:23:16
Updated On: 2020-02-18 00:23:16
Current Date: 2020-02-20 02:28:01

***** ERROR LOG 
java.lang.RuntimeException: fatal error occured while moving between floors. Seed:82988612051 depth:13
	at com.shatteredpixel.yasd.scenes.InterlevelScene.update(InterlevelScene.java:345)
	at com.watabou.noosa.Game.update(Game.java:241)
	at com.watabou.noosa.Game.step(Game.java:208)
	at com.watabou.noosa.Game.render(Game.java:143)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:494)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1573)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.shatteredpixel.yasd.actors.hero.Belongings.storeInBundle(Belongings.java:450)
	at com.shatteredpixel.yasd.actors.Char.storeInBundle(Char.java:300)
	at com.shatteredpixel.yasd.actors.mobs.Mob.storeInBundle(Mob.java:120)
	at com.watabou.utils.Bundle.put(Bundle.java:409)
	at com.shatteredpixel.yasd.levels.Level.storeInBundle(Level.java:438)
	at com.shatteredpixel.yasd.levels.RegularLevel.storeInBundle(RegularLevel.java:453)
	at com.watabou.utils.Bundle.put(Bundle.java:305)
	at com.shatteredpixel.yasd.Dungeon.saveLevel(Dungeon.java:510)
	at com.shatteredpixel.yasd.Dungeon.saveAll(Dungeon.java:520)
	at com.shatteredpixel.yasd.scenes.InterlevelScene.switchDepth(InterlevelScene.java:401)
	at com.shatteredpixel.yasd.scenes.InterlevelScene.switchDepth(InterlevelScene.java:387)
	at com.shatteredpixel.yasd.scenes.InterlevelScene.access$000(InterlevelScene.java:58)
	at com.shatteredpixel.yasd.scenes.InterlevelScene$1.run(InterlevelScene.java:129)


***** END OF LOG *****

```

```
Debug Info:
Version: 0.2.6-INDEV (406)
Seed: 82988612051
Challenge Mask: 0
```

**Comment by Smujb** [comment]
Sorry for not responding sooner; I'm not on Github that often. It seems this is an error with what is now actually a very old version - I've reworked the depth system since. Even if this error still exists, the log will not help as some of the files it refers to don't exist anymore. The latest version is actually 0.3.1, but it's in beta. Hopefully I'll be able to publicly release it soon.
