### ISSUE TITLE
Crash and other issues

### ISSUE THREAD

**Issue by vi** [Smujb/yet-another-shattered-dungeon#15]
```

***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: google
Device: crosshatch
Model: Pixel 3 XL
Manufacturer: Google
Product: crosshatch
SDK: 29
Release: 10

***** APP INFO 
Version: 0.4.4-INDEV
Installed On: 2020-02-18 00:23:16
Updated On: 2020-06-14 00:53:19
Current Date: 2020-06-14 20:32:32

***** ERROR LOG 
java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.shatteredpixel.yasd.general.levels.terrain.KindOfTerrain.solid()' on a null object reference
	at com.shatteredpixel.yasd.general.LevelHandler$1.run(LevelHandler.java:109)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.shatteredpixel.yasd.general.levels.terrain.KindOfTerrain.solid()' on a null object reference
	at com.shatteredpixel.yasd.general.levels.Level.solid(Level.java:352)
	at com.shatteredpixel.yasd.general.LevelHandler.switchDepth(LevelHandler.java:299)
	at com.shatteredpixel.yasd.general.LevelHandler.access$200(LevelHandler.java:51)
	at com.shatteredpixel.yasd.general.LevelHandler$1.run(LevelHandler.java:101)



***** END OF LOG *****

```

commit 9dfd93edd29a6ee19502a649b04d1ee821909c96

---

Other misc issues:

* Curse animation (black particles) do not disappear when item gets uncursed (e.g. using the well) on the quickslot.
* Sentry created by a wand becomes hostile when returning back to the depth where it was created. Is it intended?
* After diving out, the hero appeared at a strange location (very top left), outside the map, invisible. The game softlocked. Reloading the game does not help.
* After loading the game into underwater depth, oxygen meter did not deplete. Happened only once, when the game got updated.

**Comment by Smujb** [comment]
3 & 4 are fixed by https://github.com/Smujb/yet-another-shattered-dungeon/commit/5351987ff3775d76720f6b2a3f7e89a95f9e1aa0

**Comment by Smujb** [comment]
Oh and the main issue (the crash) is as well actually.

**Comment by Smujb** [comment]
Finally fixed the other issues.
