### ISSUE TITLE
New game crashes

### ISSUE THREAD

**Issue by ShareDVI** [Smujb/yet-another-shattered-dungeon#16]
Every time I try new game in 0.4.5b there's a crash. (tried removing app data, didn't help)

`* UCE HANDLER Library 
* by Rohit Surwase 

* DEVICE INFO 
Brand: Xiaomi
Device: nitrogen
Model: MI MAX 3
Manufacturer: Xiaomi
Product: nitrogen
SDK: 29
Release: 10.0

* APP INFO 
Version: 0.4.5b-INDEV
Installed On: 2020-03-28 06:49:49
Updated On: 2020-06-19 17:24:36
Current Date: 2020-06-19 17:24:49

* ERROR LOG 
java.lang.NullPointerException: Attempt to read from field 'boolean com.shatteredpixel.yasd.general.levels.Level.bossLevel' on a null object reference
 at com.shatteredpixel.yasd.general.Dungeon.bossLevel(Dungeon.java:413)
 at com.shatteredpixel.yasd.general.levels.Level.create(Level.java:490)
 at com.shatteredpixel.yasd.general.Dungeon.newLevel(Dungeon.java:372)
 at com.shatteredpixel.yasd.general.LevelHandler.switchDepth(LevelHandler.java:275)
 at com.shatteredpixel.yasd.general.LevelHandler.initGame(LevelHandler.java:240)
 at com.shatteredpixel.yasd.general.LevelHandler.access$300(LevelHandler.java:52)
 at com.shatteredpixel.yasd.general.LevelHandler$4.run(LevelHandler.java:208)

* END OF LOG *`

**Comment by Smujb** [comment]
0.4.5c is out and fixed this issue

**Comment by ShareDVI** [comment]
Oh, sorry, for some reason I thought b is the latest.

Nice response time!
