### ISSUE TITLE
i can't go on 5 floor, game crushes every time i try to go to next floor

### ISSUE THREAD

**Issue by Xazmadan** [Smujb/yet-another-shattered-dungeon#24]
log on crash:
***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: xiaomi
Device: daisy_sprout
Model: Mi A2 Lite
Manufacturer: Xiaomi
Product: daisy
SDK: 29
Release: 10

***** APP INFO 
Version: 0.4.8-INDEV
Installed On: 2020-07-31 14:03:14
Updated On: 2020-07-31 14:03:14
Current Date: 2020-07-31 15:35:18

***** ERROR LOG 
java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.shatteredpixel.yasd.general.sprites.CharSprite.killAndErase()' on a null object reference
	at com.shatteredpixel.yasd.general.LevelHandler$1.run(LevelHandler.java:105)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.shatteredpixel.yasd.general.sprites.CharSprite.killAndErase()' on a null object reference
	at com.shatteredpixel.yasd.general.actors.mobs.npcs.Shopkeeper.flee(Shopkeeper.java:78)
	at com.shatteredpixel.yasd.general.actors.mobs.npcs.Shopkeeper.add(Shopkeeper.java:72)
	at com.shatteredpixel.yasd.general.actors.buffs.Buff.attachTo(Buff.java:82)
	at com.shatteredpixel.yasd.general.actors.buffs.ShieldBuff.attachTo(ShieldBuff.java:45)
	at com.shatteredpixel.yasd.general.actors.buffs.Buff.append(Buff.java:149)
	at com.shatteredpixel.yasd.general.actors.buffs.Buff.affect(Buff.java:165)
	at com.shatteredpixel.yasd.general.actors.Char.live(Char.java:313)
	at com.shatteredpixel.yasd.general.actors.mobs.Mob.create(Mob.java:267)
	at com.shatteredpixel.yasd.general.actors.mobs.Mob.create(Mob.java:272)
	at com.shatteredpixel.yasd.general.levels.rooms.special.ShopRoom.placeShopkeeper(ShopRoom.java:110)
	at com.shatteredpixel.yasd.general.levels.rooms.special.ShopRoom.paint(ShopRoom.java:96)
	at com.shatteredpixel.yasd.general.levels.painters.RegularPainter.paint(RegularPainter.java:123)
	at com.shatteredpixel.yasd.general.levels.RegularLevel.build(RegularLevel.java:103)
	at com.shatteredpixel.yasd.general.levels.Level.create(Level.java:576)
	at com.shatteredpixel.yasd.general.Dungeon.newLevel(Dungeon.java:363)
	at com.shatteredpixel.yasd.general.LevelHandler.switchDepth(LevelHandler.java:274)
	at com.shatteredpixel.yasd.general.LevelHandler.access$200(LevelHandler.java:51)
	at com.shatteredpixel.yasd.general.LevelHandler$1.run(LevelHandler.java:101)

***** END OF LOG *****

**Comment by Xazmadan** [comment]
character:not matter 
equipment:not matter
items in inventroy/enemies near:not matter
also i found strange level generation, looks like pit-gen, but pit filled with random terrain blocks[Screenshot_20200731-155919.png](https://user-images.githubusercontent.com/69046303/89045314-fc7cb900-d353-11ea-998c-40e6e198d417.png)

**Comment by Smujb** [comment]
This is actually fixed by 0.4.8a
