### ISSUE TITLE
long-press inventory button cause crash with time rollback, and a rogue have issue with save, all scrap are loses even if you have scrap on previous save point

### ISSUE THREAD

**Issue by Xazmadan** [Smujb/yet-another-shattered-dungeon#27]
***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: xiaomi
Device: daisy_sprout
Model: Mi A2 Lite
Manufacturer: Xiaomi
Product: daisy
SDK: 29
Release: 10

***** APP INFO 
Version: 0.4.8a-INDEV
Installed On: 2020-07-31 17:44:13
Updated On: 2020-07-31 17:44:13
Current Date: 2020-08-07 23:08:13

***** ERROR LOG 
java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.shatteredpixel.yasd.general.windows.WndTabbed.select(WndTabbed.java:67)
	at com.shatteredpixel.yasd.general.windows.WndJournal.<init>(WndJournal.java:144)
	at com.shatteredpixel.yasd.general.ui.Toolbar$4.onLongClick(Toolbar.java:162)
	at com.watabou.noosa.ui.Button.update(Button.java:99)
	at com.watabou.noosa.Group.update(Group.java:76)
	at com.shatteredpixel.yasd.general.ui.Toolbar.update(Toolbar.java:272)
	at com.watabou.noosa.Group.update(Group.java:76)
	at com.watabou.noosa.Scene.update(Scene.java:74)
	at com.shatteredpixel.yasd.general.scenes.GameScene.update(GameScene.java:572)
	at com.watabou.noosa.Game.update(Game.java:259)
	at com.watabou.noosa.Game.step(Game.java:226)
	at com.watabou.noosa.Game.render(Game.java:157)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:494)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1577)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)

***** END OF LOG *****

**Comment by Smujb** [comment]
This crash is because the long press should open the weapons journal. Which was removed because it was broken.

**Comment by Xazmadan** [comment]
bruh, i think it must be fixed in first place just cause it can help go out situations where are you 100% dies

**Comment by Smujb** [comment]
Fixed by https://github.com/Smujb/yet-another-shattered-dungeon/commit/bc9e5a4031521e6d2c8ffb1af8846f08f90f0943
