### ISSUE TITLE
Crash when trying to inspect multiple things.

### ISSUE THREAD

**Issue by vi** [Smujb/yet-another-shattered-dungeon#3]
For example, clicking at four items in "Choose Your Hero" screen that should show some description like "The Warrior stars with a unique broken seal ...".

Also when trying to view debugging information of a savefile (tap-and-hold on hero icon). Also when pressing the `[i]` button near a challenge.

Version is 446b021843582c7b44228f8b73d17986df130862.

```
***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: google
Device: crosshatch
Model: Pixel 3 XL
Manufacturer: Google
Product: crosshatch
SDK: 29
Release: 10

***** APP INFO 
Version: 0.3.1-INDEV
Installed On: 2020-02-18 00:23:16
Updated On: 2020-05-01 00:23:28
Current Date: 2020-05-01 00:31:13

***** ERROR LOG 
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
	at com.shatteredpixel.yasd.general.windows.WndMessage.<init>(WndMessage.java:46)
	at com.shatteredpixel.yasd.general.windows.WndStartGame$HeroPane$3.onClick(WndStartGame.java:316)
	at com.watabou.noosa.ui.Button$1.onClick(Button.java:67)
	at com.watabou.noosa.PointerArea.onSignal(PointerArea.java:85)
	at com.watabou.noosa.PointerArea.onSignal(PointerArea.java:33)
	at com.watabou.utils.Signal.dispatch(Signal.java:81)
	at com.watabou.input.PointerEvent.processPointerEvents(PointerEvent.java:99)
	at com.watabou.input.InputHandler.processAllEvents(InputHandler.java:44)
	at com.watabou.noosa.Game.update(Game.java:249)
	at com.watabou.noosa.Game.step(Game.java:218)
	at com.watabou.noosa.Game.render(Game.java:149)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:494)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1573)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)



***** END OF LOG *****
```

**Comment by Smujb** [comment]
I have fixed this error and it will release the fixed version soon.
